# This file is autogenerated. Do not edit this file.
# It may be replaced when you upgrade to new versions of watircraft.

# Generated at Mon Jan 04 21:53:05 -0800 2010
# Generated by watircraft 0.5.0

ENV['ENVIRONMENT'] ||= "test"
APP_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..')) unless defined?(APP_ROOT)

require 'watircraft'